//
//  InstanceMethodInterceptor+SingleIntVoid.swift
//  ChouTi
//
//  Copyright © 2020 Honghao Zhang.
//
//  MIT License
//
//  Copyright (c) 2020 Honghao Zhang (github.com/honghaoz)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to
//  deal in the Software without restriction, including without limitation the
//  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
//  sell copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
//  IN THE SOFTWARE.
//

// Generated by generate_single_arg_void.sh. Do not edit directly.

import Foundation
import ObjectiveC

extension InstanceMethodInterceptor {

  private typealias VoidMethodWithIntIMP = @convention(c) (AnyObject, Selector, Int) -> Void

  static func addSubclassOverrideWithIntIfNeeded(
    subclass: AnyClass,
    originalClass: AnyClass,
    selector: Selector
  ) {
    let key = "\(NSStringFromClass(subclass))|\(NSStringFromSelector(selector))"

    subclassSelectorOverridesLock.lock()
    if subclassSelectorOverrides.contains(key) {
      subclassSelectorOverridesLock.unlock()
      return
    }
    subclassSelectorOverrides.insert(key)
    subclassSelectorOverridesLock.unlock()

    guard let originalMethod = class_getInstanceMethod(originalClass, selector) else {
      ChouTi.assertFailure("Failed to get original method for subclass override") // impossible
      return
    }

    let originalImplementation = unsafeBitCast(
      class_getMethodImplementation(originalClass, selector),
      to: VoidMethodWithIntIMP.self
    )

    let newImplementation: @convention(block) (AnyObject, Int) -> Void = { object, arg in
      let callOriginal: (Any?) -> Void = { value in
        guard let typedValue = value as? Int else {
          let actualTypeDescription: String
          if let value {
            actualTypeDescription = String(describing: type(of: value))
          } else {
            actualTypeDescription = "nil"
          }
          ChouTi.assertFailure("intercept arg type mismatch", metadata: [
            "selector": NSStringFromSelector(selector),
            "expected": String(describing: Int.self),
            "actual": actualTypeDescription,
          ])
          return
        }
        originalImplementation(object, selector, typedValue)
      }
      invokeHooksWithAnyArg(on: object, selector: selector, arg: arg, callOriginal: callOriginal)
    }

    let methodTypeEncoding = method_getTypeEncoding(originalMethod)
    let newIMP = imp_implementationWithBlock(newImplementation)
    class_addMethod(subclass, selector, newIMP, methodTypeEncoding)
    subclassMethodIMPs.append(newIMP)
  }

  /// Swizzles the original class method (single argument) when KVO has already swizzled the instance.
  static func swizzleOriginalMethodWithInt(
    originalClass: AnyClass,
    selector: Selector
  ) {
    let key = methodKey(originalClass: originalClass, selector: selector)

    swizzledMethodsLock.lock()
    if swizzledMethods.contains(key) {
      swizzledMethodsLock.unlock()
      return
    }
    swizzledMethods.insert(key)
    swizzledMethodsLock.unlock()

    guard let originalMethod = class_getInstanceMethod(originalClass, selector) else {
      ChouTi.assertFailure("Failed to get method for original class swizzling") // impossible
      return
    }

    let originalIMP = method_getImplementation(originalMethod)
    let originalImplementation = unsafeBitCast(originalIMP, to: VoidMethodWithIntIMP.self)

    let newImplementation: @convention(block) (AnyObject, Int) -> Void = { object, arg in
      let callOriginal: (Any?) -> Void = { value in
        guard let typedValue = value as? Int else {
          let actualTypeDescription: String
          if let value {
            actualTypeDescription = String(describing: type(of: value))
          } else {
            actualTypeDescription = "nil"
          }
          ChouTi.assertFailure("intercept arg type mismatch", metadata: [
            "selector": NSStringFromSelector(selector),
            "expected": String(describing: Int.self),
            "actual": actualTypeDescription,
          ])
          return
        }
        originalImplementation(object, selector, typedValue)
      }
      invokeHooksWithAnyArg(on: object, selector: selector, arg: arg, callOriginal: callOriginal)
    }

    let newIMP = imp_implementationWithBlock(newImplementation)
    method_setImplementation(originalMethod, newIMP)

    swizzledMethodOriginalIMPsLock.lock()
    swizzledMethodOriginalIMPs[key] = originalIMP
    swizzledMethodOriginalIMPsLock.unlock()

    swizzledMethodIMPsLock.lock()
    swizzledMethodIMPs[key] = newIMP
    swizzledMethodIMPsLock.unlock()
  }
}
