name: build
on:
  push:
    branches-ignore:
      - "github-actions/**" # ignore github-actions branches
      - "dependabot/**" # ignore dependabot branches
  pull_request: # any pull request against any branch
  workflow_dispatch: # manual trigger to run workflow
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # * * * * *
    - cron: "0 1,15 * * *" # every day at 1:00 UTC (17:00 PST, 18:00 PDT) and 15:00 UTC (7:00 PST, 8:00 PDT)

env:
  TERM: xterm-256color
  MACOS: ${{ vars.MACOS }}
  XCODE_VERSION: ${{ vars.XCODE_VERSION }}
  DEVELOPER_DIR: /Applications/Xcode_${{ vars.XCODE_VERSION }}.app/Contents/Developer

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        xcode: [Xcode_15.3]
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Bootstrap
        run: make bootstrap
      # ChouTi
      - name: Test package "ChouTi"
        if: success() || failure()
        run: make test -C packages/ChouTi
      - name: Test package "ChouTi" with Codecov
        if: success() || failure()
        run: make test-codecov -C packages/ChouTi
      - name: Upload coverage reports to Codecov (ChouTi)
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/ChouTi/.build/debug/codecov/coverage.lcov
          disable_search: true
          flags: ChouTi
          name: ChouTi
          fail_ci_if_error: true
      # ChouTiTest
      - name: Test package "ChouTiTest"
        if: success() || failure()
        run: make test-codecov -C packages/ChouTiTest
      - name: Upload coverage reports to Codecov (ChouTiTest)
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: packages/ChouTiTest/.build/debug/codecov/coverage.lcov
          disable_search: true
          flags: ChouTiTest
          name: ChouTiTest
          fail_ci_if_error: true
      - name: Build root package
        if: success() || failure()
        run: make build
